In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r'../data/credit_score_prediction.csv')
df.head()

,customer_id,age,annual_income,employment_years,credit_utilization,payment_history,num_credit_cards,loan_balance,debt_to_income,credit_inquiries,credit_score
0,C000001,35,40248,17,5.8,Excellent,1,51889,0.33,9,850
1,C000002,35,67293,35,75.2,Good,3,93494,0.52,9,589
2,C000003,39,118802,30,31.7,Excellent,1,30989,0.50,9,784
3,C000004,50,58695,5,31.7,Good,7,51565,0.40,8,771
4,C000005,25,69854,21,16.9,Good,3,36061,0.73,4,837

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         1000 non-null   object
 1   age                 1000 non-null   int64
 2   annual_income       1000 non-null   int64
 3   employment_years    1000 non-null   int64
 4   credit_utilization  1000 non-null   float64
 5   payment_history     1000 non-null   object
 6   num_credit_cards    1000 non-null   int64
 7   loan_balance        1000 non-null   int64
 8   debt_to_income      1000 non-null   float64
 9   credit_inquiries    1000 non-null   int64
 10  credit_score        1000 non-null   int64
dtypes: float64(2), int64(7), object(2)
memory usage: 86.1+ KB

In [6]:
df.drop(columns = ['customer_id'], axis = 1, inplace = True)

In [7]:
df.head()

,age,annual_income,employment_years,credit_utilization,payment_history,num_credit_cards,loan_balance,debt_to_income,credit_inquiries,credit_score
0,35,40248,17,5.8,Excellent,1,51889,0.33,9,850
1,35,67293,35,75.2,Good,3,93494,0.52,9,589
2,39,118802,30,31.7,Excellent,1,30989,0.50,9,784
3,50,58695,5,31.7,Good,7,51565,0.40,8,771
4,25,69854,21,16.9,Good,3,36061,0.73,4,837

In [8]:
df['payment_history'].value_counts()

payment_history
Good         271
Poor         258
Excellent    246
Average      225
Name: count, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()

In [11]:
df['payment_history'] = le.fit_transform(df['payment_history'])

In [12]:
df.head()

,age,annual_income,employment_years,credit_utilization,payment_history,num_credit_cards,loan_balance,debt_to_income,credit_inquiries,credit_score
0,35,40248,17,5.8,1,1,51889,0.33,9,850
1,35,67293,35,75.2,2,3,93494,0.52,9,589
2,39,118802,30,31.7,1,1,30989,0.50,9,784
3,50,58695,5,31.7,2,7,51565,0.40,8,771
4,25,69854,21,16.9,2,3,36061,0.73,4,837

In [13]:
df['num_credit_cards'].value_counts()

num_credit_cards
8    145
7    137
1    128
2    127
3    123
6    117
5    116
4    107
Name: count, dtype: int64

In [14]:
x = df.drop(columns = ['credit_score'], axis = 1)
y = df['credit_score']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [17]:
x_train.shape, x_test.shape

((800, 9), (200, 9))

In [18]:
y_train.shape, y_test.shape

((800,), (200,))

In [19]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from xgboost import XGBRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [20]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [21]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(),
    "Lasso Regression": Lasso(),
    "Decision Tree": DecisionTreeRegressor(random_state = 42),
    "Random Forest": RandomForestRegressor(n_estimators = 100, random_state = 42),
    "Gradient Boosting": GradientBoostingRegressor(random_state = 42),
    "AdaBoost": AdaBoostRegressor(random_state = 42),
    "Support Vector Regressor": SVR(),
    "K-Nearest Neighbors": KNeighborsRegressor(n_neighbors = 10),
    "XGBoost" : XGBRegressor(n_estimators = 100)
}

In [22]:
results = []

for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = root_mean_squared_error(y_test, y_pred)

    results.append({
        'Model Name: ' : name,
        'R2 Score' : r2,
        'Mean Absolute Error' : mae,
        'Mean Squared Error' : mse,
        'Root Mean Squared Error' : rmse
    })

    print('\n' + '-' * 45)
    print('Model:', name)
    print('R2 Score:', r2)
    print('Mean Absolute Error:', mae)
    print('Mean Squared Error:', mse)
    print('Root Mean Squared Error:', rmse)

summary_df = pd.DataFrame(results).sort_values(by = "R2 Score", ascending = False)
summary_df.index = range(1, len(summary_df) + 1)

print('\n' + '=' * 45)
print('MODEL SUMMARY')
print('=' * 45)
summary_df

---------------------------------------------
Model: Linear Regression
R2 Score: 0.7794514009511591
Mean Absolute Error: 33.152863225896674
Mean Squared Error: 1545.1221927247232
Root Mean Squared Error: 39.30804234154537

---------------------------------------------
Model: Ridge Regression
R2 Score: 0.7794466897659729
Mean Absolute Error: 33.15539687136658
Mean Squared Error: 1545.155198406086
Root Mean Squared Error: 39.30846217299891

---------------------------------------------
Model: Lasso Regression
R2 Score: 0.7790669396674342
Mean Absolute Error: 33.222076960188524
Mean Squared Error: 1547.8156564977348
Root Mean Squared Error: 39.34228839935134

---------------------------------------------
Model: Decision Tree
R2 Score: 0.8199088327763655
Mean Absolute Error: 29.255
Mean Squared Error: 1261.685
Root Mean Squared Error: 35.520205517423456

---------------------------------------------
Model: Random Forest
R2 Score: 0.9138329002090696
Mean Absolute Error: 20.721949999999996
Mean Squared Error: 603.6705685
Root Mean Squared Error: 24.569708351952407

---------------------------------------------
Model: Gradient Boosting
R2 Score: 0.9240546544260456
Mean Absolute Error: 19.51474911695198
Mean Squared Error: 532.0588722237993
Root Mean Squared Error: 23.06640137134094

---------------------------------------------
Model: AdaBoost
R2 Score: 0.884166757197103
Mean Absolute Error: 23.392588250969084
Mean Squared Error: 811.5060121982126
Root Mean Squared Error: 28.4869445921849

---------------------------------------------
Model: Support Vector Regressor
R2 Score: -0.0071170849742387965
Mean Absolute Error: 69.34846148432274
Mean Squared Error: 7055.6737398332825
Root Mean Squared Error: 83.99805795274843

---------------------------------------------
Model: K-Nearest Neighbors
R2 Score: -0.04327491823388052
Mean Absolute Error: 70.5295
Mean Squared Error: 7308.98875
Root Mean Squared Error: 85.49262395084152

---------------------------------------------
Model: XGBoost
R2 Score: 0.8998337388038635
Mean Absolute Error: 22.04604721069336
Mean Squared Error: 701.7462768554688
Root Mean Squared Error: 26.490493774414062

=============================================
MODEL SUMMARY
=============================================

,Model Name:,R2 Score,Mean Absolute Error,Mean Squared Error,Root Mean Squared Error
1,Gradient Boosting,0.924055,19.514749,532.058872,23.066401
2,Random Forest,0.913833,20.721950,603.670568,24.569708
3,XGBoost,0.899834,22.046047,701.746277,26.490494
4,AdaBoost,0.884167,23.392588,811.506012,28.486945
5,Decision Tree,0.819909,29.255000,1261.685000,35.520206
6,Linear Regression,0.779451,33.152863,1545.122193,39.308042
7,Ridge Regression,0.779447,33.155397,1545.155198,39.308462
8,Lasso Regression,0.779067,33.222077,1547.815656,39.342288
9,Support Vector Regressor,-0.007117,69.348461,7055.673740,83.998058
10,K-Nearest Neighbors,-0.043275,70.529500,7308.988750,85.492624

In [23]:
a = GradientBoostingRegressor(random_state = 42)
a.fit(x_train, y_train)

GradientBoostingRegressor(random_state=42)

In [24]:
import pickle

In [26]:
with open('../artifact/credit_score.pkl', 'wb') as f:
    pickle.dump(a, f)

with open('../artifact/encoder.pkl', 'wb') as f:
    pickle.dump(le, f)